default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: workout_record_app_development

test:
  <<: *default
  database: workout_record_app_test

production:
  adapter: postgresql
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
